"""add competency framework

Revision ID: 4ddd9432d12b
Revises: ea258e582a62
Create Date: 2026-09-15 21:13:58.310128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ddd9432d12b'
down_revision: Union[str, Sequence[str], None] = 'ea258e582a62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competencies_organization_id'), 'competencies', ['organization_id'], unique=False)
    op.create_table('interview_competencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('interview_definition_id', sa.Uuid(), nullable=False),
    sa.Column('competency_id', sa.Uuid(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('target_level', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['interview_definition_id'], ['interview_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_definition_id', 'competency_id', name='uq_interview_competency')
    )
    op.create_index(op.f('ix_interview_competencies_competency_id'), 'interview_competencies', ['competency_id'], unique=False)
    op.create_index(op.f('ix_interview_competencies_interview_definition_id'), 'interview_competencies', ['interview_definition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_competencies_interview_definition_id'), table_name='interview_competencies')
    op.drop_index(op.f('ix_interview_competencies_competency_id'), table_name='interview_competencies')
    op.drop_table('interview_competencies')
    op.drop_index(op.f('ix_competencies_organization_id'), table_name='competencies')
    op.drop_table('competencies')
    # ### end Alembic commands ###
