"""create_questions_table

Revision ID: bf19f09bc1bf
Revises: cc2e9c4b7e25
Create Date: 2026-09-15 22:42:29.850142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf19f09bc1bf'
down_revision: Union[str, Sequence[str], None] = 'cc2e9c4b7e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('interview_definition_id', sa.Uuid(), nullable=False),
    sa.Column('competency_id', sa.Uuid(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('expected_signal', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('difficulty_level >= 1 AND difficulty_level <= 5', name='chk_question_difficulty_level'),
    sa.CheckConstraint('display_order >= 1', name='chk_question_display_order'),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['interview_definition_id'], ['interview_definitions.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_competency_id'), 'questions', ['competency_id'], unique=False)
    op.create_index(op.f('ix_questions_interview_definition_id'), 'questions', ['interview_definition_id'], unique=False)
    op.create_index(op.f('ix_questions_organization_id'), 'questions', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_organization_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_interview_definition_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_competency_id'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
