"""create intake requests table

Revision ID: ea258e582a62
Revises: b066d22dcb0b
Create Date: 2026-09-15 19:41:30.492905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea258e582a62'
down_revision: Union[str, Sequence[str], None] = 'b066d22dcb0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intake_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('interview_definition_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['interview_definition_id'], ['interview_definitions.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name='uq_intake_requests_organization_idempotency_key')
    )
    op.create_index(op.f('ix_intake_requests_interview_definition_id'), 'intake_requests', ['interview_definition_id'], unique=False)
    op.create_index(op.f('ix_intake_requests_job_id'), 'intake_requests', ['job_id'], unique=False)
    op.create_index(op.f('ix_intake_requests_organization_id'), 'intake_requests', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intake_requests_organization_id'), table_name='intake_requests')
    op.drop_index(op.f('ix_intake_requests_job_id'), table_name='intake_requests')
    op.drop_index(op.f('ix_intake_requests_interview_definition_id'), table_name='intake_requests')
    op.drop_table('intake_requests')
    # ### end Alembic commands ###
